POST http://34.146.142.76/login HTTP/1.1
Content-Type: application/json

{"Token": ""}

###

GET http://34.146.142.76/

###

POST http://34.146.142.76/update HTTP/1.1
Content-Type: application/json

{"LoginToken": ""}
