POST https://api.hello-slide.jp/account/login HTTP/1.1
Content-Type: application/json

{"Token": ""}

###

GET https://api.hello-slide.jp/account/

###

POST https://api.hello-slide.jp/account/update HTTP/1.1
Content-Type: application/json

{"LoginToken": ""}
